/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a03ex04;

import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class Tela extends javax.swing.JFrame {

    private int sorteio1;
    private int sorteio2;
    private int acertos = 0;
    private int erros = 0;
    private int s1 = 0;
    private int s2 = 0;
    private int s3 = 0;
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        btnResposta1 = new javax.swing.JButton();
        btnResposta2 = new javax.swing.JButton();
        btnResposta3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Soma 2.0");
        setResizable(false);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");

        jLabel2.setText("+");

        lblValor1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblValor1.setText("0");

        lblValor2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblValor2.setText("0");

        jLabel3.setText("Pontuação:");

        lblAcertos.setText("000");

        lblErros.setText("000");

        lblStatus1.setText("...");

        btnResposta1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnResposta1.setText("0");
        btnResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta1ActionPerformed(evt);
            }
        });

        btnResposta2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnResposta2.setText("0");
        btnResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta2ActionPerformed(evt);
            }
        });

        btnResposta3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnResposta3.setText("0");
        btnResposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNovo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValor1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnResposta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblAcertos)
                        .addComponent(lblErros))
                    .addComponent(btnNovo))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblStatus1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        sorteio1 = (int)(Math.random()*10);
        sorteio2 = (int)(Math.random()*10);        
        lblValor1.setText(""+sorteio1);
        lblValor2.setText(""+sorteio2);
//        btnJogar.setEnabled(true);
        btnNovo.setEnabled(false);
//        txtJogar.setText("");// limpando a caixa de texto
//        txtJogar.requestFocus(); // chamar o foco
//        s1 = (int)(Math.random()*19);
//        s2 = (int)(Math.random()*19);
//        s3 = (int)(Math.random()*19);
//        btnResposta1.setText(""+s1);
//        btnResposta2.setText(""+s2);
//        btnResposta3.setText(""+s3);
        int botaoRespostaCorreta = (int)(Math.random()*3);
        int r = sorteio1+sorteio2;
        if (botaoRespostaCorreta == 0){
            btnResposta1.setText(""+r); // correto
            btnResposta2.setText(""+(r+1));
            btnResposta3.setText(""+(r-1));
        }
        else if (botaoRespostaCorreta == 1){
            btnResposta1.setText(""+(r+1));
            btnResposta2.setText(""+r); // correto
            btnResposta3.setText(""+(r-1));
        }
        else{
            btnResposta1.setText(""+(r+1));
            btnResposta2.setText(""+(r-1));
            btnResposta3.setText(""+r); // correto
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta1ActionPerformed
        chkResposta(1);
    }//GEN-LAST:event_btnResposta1ActionPerformed

    private void btnResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta2ActionPerformed
        chkResposta(2);
    }//GEN-LAST:event_btnResposta2ActionPerformed

    private void btnResposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta3ActionPerformed
        chkResposta(3);
    }//GEN-LAST:event_btnResposta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResposta1;
    private javax.swing.JButton btnResposta2;
    private javax.swing.JButton btnResposta3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    // End of variables declaration//GEN-END:variables

    private void chkResposta(int botao) {
        String p = btnResposta1.getText();        
        if (botao == 2)
            p = btnResposta2.getText();
        else if (botao == 3)
            p = btnResposta3.getText();
        int resposta = Integer.parseInt(p);
        String msg = "";
        if (resposta == sorteio1+sorteio2){
            // acertou
            acertos++;
            lblAcertos.setText(""+acertos);
            msg = "Você acertou!";
            JOptionPane.showMessageDialog(null, msg);
        }
        else{
            // errou
            erros++;
            lblErros.setText(""+erros);
            msg = "Você errou!";
            JOptionPane.showMessageDialog(null, msg, "Meu jogo", JOptionPane.ERROR_MESSAGE);
        }
        btnNovo.setEnabled(true);
        lblStatus1.setText(msg);
    }
}
